name: CI/CD for Golang Demo

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          docker build -t <account_id>.dkr.ecr.us-east-1.amazonaws.com/silly-demo:$TAG .
          docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/silly-demo:$TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name golang-demo-cluster

      - name: Deploy to EKS with Helm
        run: |
          helm upgrade --install silly-demo ./silly-demo \
            --set image.repository=<account_id>.dkr.ecr.us-east-1.amazonaws.com/silly-demo \
            --set image.tag=${{ env.TAG }}
