golangApp:
  image: "golang-demo:latest"

nginx:
  image: nginx:latest

postgres:
  image: postgres:13
  user: postgres
  password: postgres_password
  db: db
  host: postgres

service:
  port: 80  


serviceAccount:
  create: false

ingress:
  enabled: false  
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []  

