apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: golang-app
          image: {{ .Values.golangApp.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASS
              value: {{ .Values.postgres.password }}
            - name: DB_NAME
              value: {{ .Values.postgres.db }}
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
