apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: nginx
    - port: 8080
      targetPort: 8080
      name: golang-app
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: {{ .Chart.Name }}
